service: api-infra-cli

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ec2:DescribeInstances'
      Resource: '*'

functions:
  list_instances:
    handler: src.handler.list_instances
    events:
      - http:
          path: instances
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline
