service: api-infra-cli

provider:
  name: aws
  runtime: python3.8

functions:
  list_instances:
    handler: handler.list_instances
    events:
      - http:
          path: instances
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline
